### PR TITLE
Ddd core conservation 08 01 2020

### PR DESCRIPTION
**Pull request by Paulmulonzia**
Date fields are not being correctly represented in cspace.

Converter is picking dates in the format dd-mm-yy or yy-mm-dd but sample data provided has the format mm-dd-yy.

### CODE REVIEW

**Comment by mark-cooper** [comment]
@Paulmulonzia looks like this PR has conservation & conditioncheck. I recommend we only do one authority / procedure per PR to make things easier to review. Is the conditioncheck here different from: https://github.com/collectionspace/cspace-converter/pull/172 ?

**Comment by Paulmulonzia** [comment]
Hi @mark-cooper, I will push a new branch for conservation.

Thanks.

**Comment by mark-cooper** [comment]
@Paulmulonzia thx, I'll close this branch when the new one is ready.

**Comment by mark-cooper** [comment]
@Paulmulonzia quick note. Make sure new branch is based on latest master. Some of the XML helper method names were updated so you'll want to be up to date with those.

**Comment by Paulmulonzia** [comment]
sure thing @mark-cooper, 

Thanks.

**Pull request closed without merging**
