### PR TITLE
Extension as module

### PR DESCRIPTION
**Pull request by mark-cooper**

### CODE REVIEW

**Comment by kspurgin** [comment]
With you 100% on extensions just being modules and not classed. I ran into this with setting up the socialMedia extension for public art (which gets used in Person and Organization records), and realized it's a better way.

I also noticed yesterday that sometimes we've something like: 

AnthroCollectionObject < CoreCollectionObject < CollectionObject

and sometimes we've done: 
 
AnthroCollectionObject < CollectionObject

The latter seems more correct if either is, since nothing's really getting defined by or inherited from the middle level, but it made me question what the point of these classes are if we're just building up a CollectionObject via the Anthro module. 

There's a one thing I don't like about this PR though: 
- I really don't want to manage all the extensions in one big extensions.rb file (and all their tests in another big test file)

Another thing to keep in mind is some extensions (at least one) has separate fields set up for different record types. I'm thinking nagpra, which extends claim and collectionobject. I think a separate Extension::Nagpra or Extension::CulturalCare or whatever works better to support the modular nature of the individual extensions. 

I'll update my PR to reflect a sort of compromise between what it is now and what you've done here, and see if that looks ok to you... 

Can you say more about what the `docs/test/LHMC.md` file is? Is that some kind of playbook for automation tied into Github CI or something?

**Comment by kspurgin** [comment]
@mark-cooper -- the compromise version of #286  is ready for review

**Comment by mark-cooper** [comment]
Hey @kspurgin I hadn't noticed we have (or had) things like: `AnthroCollectionObject < CoreCollectionObject < CollectionObject`. We definitely don't want that. For refactoring from class to instance methods we'll ultimately want to inherit directly where classes need to override or build on parent methods, so `AnthroCollectionObject < CoreCollectionObject` would be correct, as would `OHCCollectionObject < AnthroCollectionObject` (and it looks like that's already in place, which is good).

"I really don't want to manage all the extensions in one big extensions.rb file (and all their tests in another big test file)"

Yeah, sounds good. I wasn't expecting that to last long term.

"Can you say more about what the docs/test/LHMC.md file is? Is that some kind of playbook for automation tied into Github CI or something?"

It's just the doc convention I came up for Paul, nothing clever. I was pointing him at those docs for getting setup quick and showing the exact set of config + steps that could be taken (and that I could replicate if needed). But when I've been away for a while I actually find them useful as my starting point for getting up and running again. I think they'll be good for the UCB devs who will be contributing soonish. I noticed that you started updating the wiki so that's probably a better place for the docs and we can shuffle them there if you think that's better.

**Comment by kspurgin** [comment]
Hi @mark-cooper To clarify, I haven't seen anything literally like `AnthroCollectionObject < CoreCollectionObject < CollectionObject` in our code. 

However (and I can't remember exactly what I saw it on) I did notice sometimes we have something like `AnthroCollectionObject < CoreCollectionObject` defined, and sometimes we have done it like `AnthroCollectionObject < CollectionObject` (skipping the CoreCollectionObject level of inheritance).

**Comment by mark-cooper** [comment]
Got it. The skipping part is incorrect if we ever want to transition from class methods. This looks good:

CoreCollectionObject < CollectionObject
AnthroCollectionObject < CoreCollectionObject
OHCCollectionObject < AnthroCollectionObject

**Comment by mark-cooper** [comment]
https://github.com/collectionspace/cspace-converter/pull/286

**Pull request closed without merging**
