### PR TITLE
Concept/Nomenclature module

### LINKED ISSUE #92: Converter profile for Nomenclature_Core_All
Mapping

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/concept.rb

Data

https://github.com/lyrasis/cspace-converter/blob/master/data/core/authconcept_nomenclature_terms.csv

Config: use "core"

https://github.com/lyrasis/cspace-converter/blob/master/DEV.md#core

Start by manually creating a record in cspace using first row of sample data. Export the XML then delete the record from cspace. Make a PR including the reference XML (spec/fixtures/files/) and initial mapping spec (spec/collectionspace/converter/core/). From the converter you can use: bundle exec rake remote:get[acquisitions/$csid] to get the XML.

Implement fields not covered in mapping currently.

### PR DESCRIPTION
**Pull request by kspurgin**
fixes #92

### CODE REVIEW

**Comment by kspurgin** [comment]
@mark-cooper So this currently takes the data from the data/core/authconcept_nomenclature_terms.csv and converts it to basic/plain concept XML ([spec/fixtures/files/core_concept.xml](https://github.com/collectionspace/cspace-converter/blob/nomenclature-module/spec/fixtures/files/core_concept.xml))

I added the default nomenclature field values to lib/collectionspace/converter/core/config.yml but am not sure how to set up a spec to test that it will produce [the desired Nomenclature-specific xml](https://github.com/collectionspace/cspace-converter/blob/nomenclature-module/spec/fixtures/files/core_concept_nomenclature.xml). 

I'll look around for an example to follow, but if you have any suggestions, lemme know.

**Comment by kspurgin** [comment]
n/m -- I found this which is I presume what I need: https://github.com/collectionspace/cspace-converter/blob/18ae73b77b7b056cfc1883d461c4421c05b3ad31/spec/collectionspace/converter/core/person_spec.rb#L5

**Comment by kspurgin** [comment]
I have reset the cache. 

When I have termlanguage set in the nomenclature config as: English, I'm getting this spec failure: 

`
Xpath match failure: /document/*/conceptTermGroupList/conceptTermGroup/termLanguage
urn:cspace:core.collectionspace.org:vocabularies:name(languages):item:name(english)'English'
urn:cspace:core.collectionspace.org:vocabularies:name(languages):item:name(eng)'English'
`

When I have termlanguage set in the nomenclature config as: eng I'm getting this spec failure: 

`
Xpath match failure: /document/*/conceptTermGroupList/conceptTermGroup/termLanguage
urn:cspace:core.collectionspace.org:vocabularies:name(languages):item:name(eng)'eng'
urn:cspace:core.collectionspace.org:vocabularies:name(languages):item:name(eng)'English'
`

I just downloaded fresh, remote XML for a concept and verified it still wants: 
`
urn:cspace:core.collectionspace.org:vocabularies:name(languages):item:name(eng)'English'
`

My code to set the language is basically copied directly from the person.rb module. 
Mine: 
https://github.com/collectionspace/cspace-converter/blob/ed009370e85c7160c58c822ab56ebdd4685b3463/lib/collectionspace/converter/core/concept.rb#L20

Person: 
https://github.com/collectionspace/cspace-converter/blob/ed009370e85c7160c58c822ab56ebdd4685b3463/lib/collectionspace/converter/core/person.rb#L44

What am I missing, @mark-cooper ?

**Comment by mark-cooper** [comment]
@kspurgin this fixes it:

```diff
-    '/document/*/conceptTermGroupList/conceptTermGroup/termLanguage',
+    { xpath: "/document/*/conceptTermGroupList/conceptTermGroup/termLanguage", transform: ->(text) { CSURN.parse(text)[:label].downcase } },
```

In the test context there is no cache. So when the reference XML contains refnames we need the transform lambda to standardize the text that gets compared.

**Comment by kspurgin** [comment]
Thanks, I'll incorporate that!

**Comment by mark-cooper** [comment]
@kspurgin I'm erring on the side of caution and including the `shortIdentifier` in our authority XML records like this:

https://github.com/collectionspace/cspace-converter/blob/master/lib/collectionspace/converter/core/person.rb#L14-L29

It may not be strictly necessary at this time because a) the CT will find or create an identifier in a way that should be consistent already and b) I don't believe CollectionSpace is generally respecting the uniqueness of identifiers. However I think being explicit is good for clarity, and if uniqueness of identifiers is enforced in the future (or is already in place for short identifiers?) then including it would prevent a potential source of record duplication.

This bit isn't supported yet, but it should be:

https://github.com/collectionspace/cspace-converter/pull/137/files#diff-28e1f85bd0a18233e5f3a2beae580c88R197-R203

It's fine to leave it in. I'll get to it this week and start adding overdue tests for the import service.

**Comment by kspurgin** [comment]
@mark-cooper The latest commit adds the shortIdentifier code as requested. 

HOWEVER, I am not seeing the shortIdentifier being output in the converted XML for the concept [OR for persons](https://gist.github.com/kspurgin/31aef05c9e79abe2827bb74f47e6a1ec)

I don't see an identifier key in the config.yml file for person at all, and adding it for nomenclature didn't seem to have an effect. 

Am I missing something?

**Comment by kspurgin** [comment]
By "This bit isn't supported yet, but it should be:" are you referring to the fact that we don't have a basic concept config set up yet? 

Or something else?

**Comment by mark-cooper** [comment]
No, I'm referring to the use of the `Authorities` and `Vocabularies` keys in the `config` section when the type is an authority. That won't do anything currently. The only keys supported there are `name_field`, `authority_type` and `authority_subtype`, the other stuff will be ignored.

I'm definitely seeing the `shortIdentifier` on the master branch for person records. I'll try your branch soon.

**Comment by kspurgin** [comment]
I'll merge the current master into my branch and see...

**Comment by kspurgin** [comment]
@mark-cooper I've updated this to support all concept fields. 

I cannot figure out how to test the addition of `shortIdentifier` -- not sure if we need to. 

I also cannot make any sense of how to set up the config.yml for this. That's probably worth a discussion?

Signing off for today, though...

**Comment by kspurgin** [comment]
Also, I spent about 40 minutes trying to pass the test: 

`2) CollectionSpace::Tools::Lookup can find converter class names returns the converter remote host
     Failure/Error:
       expect(
       Lookup.converter_remote_host
       ).to eq 'localhost'
     
       expected: "localhost"
            got: "core.dev.collectionspace.org"`

At a loss on that one, too.

**Comment by kspurgin** [comment]
@mark-cooper I believe this is ready.

It supports all possible fields in a concept record. 

*I believe it also fixes the problems @meganforbes was having importing sample data and OHC data*

I added rows in the osteology and anthro collectionobject sample data that only have values in the required fields. I wrote tests checking that those rows were getting processed as expected.  They seem to be, so I *think* that's the end of that nil value-related error.

**Comment by mark-cooper** [comment]
LGTM 👍

**Pull request merged**
